Drop now unused lambda capture
tokenProvider is unused inside the lambda since
691ff3953172bf850b52af8aa6e6980dd94bc9d6,
triggering

        .../qt5/qtwayland/src/plugins/shellintegration/xdg-shell/qwaylandxdgshell.cpp:574:32: error: lambda capture 'tokenProvider' is not used [-Werror,-Wunused-lambda-capture]
          574 |                         [this, tokenProvider](const QString &token) {

in a local clang 19 build.

Pick-to: 6.8
Change-Id: I69f7884afee46859c66a46edce3e7a8001c60e22
Reviewed-by: David Edmundson <davidedmundson@kde.org>
Reviewed-by: David Redondo <qt@david-redondo.de>
(cherry picked from commit c0471e22a0319afa9f8404b908619192ff0de06d)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>